Added a custom recipe system to (de-) serialize recipes via the config
DRE2N/CaliburnAPI pull request #11
Opened 2021-03-04 23:26 UTC by Fyreum

Ich habe ein System aufgebaut, mit dem man Rezepte über die config erstellen und registrieren kann. Als Bestandteile und Resultate können ExItems, sowie Standard Materialien genutzt werden. Ein serialized recipe wird als einzelner String in der Config gespeichert und später wieder geladen.

2021-03-10 17:05 UTC, Malfrador requested changes

2021-03-10 17:05 UTC, Malfrador commented on .idea/.gitignore
> +/workspace.xml
Die sollten nicht committed werden ^^

2021-03-10 17:05 UTC, Malfrador commented on .idea/.name
> +caliburn
Genauso, IntelliJ-Datei

2021-03-10 17:05 UTC, Malfrador commented on src/main/java/de/erethon/caliburn/item/CustomItem.java
> +
Viel diff für eigentlich keine Änderung, aber nicht _sooo_ schlimm.

2021-03-10 17:05 UTC, Malfrador commented on src/main/java/de/erethon/caliburn/category/Category.java
> +    public static final Category<ExItem> BASE_STONE_OVERWORLD = new Category<>("base_stone_overworld", STONE, GRANITE, DIORITE, ANDESITE);
Was ist hier passiert?

2021-03-10 17:05 UTC, Malfrador commented on src/main/java/de/erethon/caliburn/util/SecuredStringBuilder.java
> +}
Das wäre evtl. eine schöne Klasse für Commons

2021-03-10 17:05 UTC, Malfrador commented on src/main/java/de/erethon/caliburn/util/Util.java
> +    public static char getChar(int i) {
ASCII, pleaaase. Characters#forDigit() oder sowas müsste es auch geben.
```suggestion
    public static char getChar(int i) {
    return (char) (i + '0');
}
```

2021-03-10 19:16 UTC, Sataniel98 reviewed
Ich kann zur Funktionalität erstmal nicht so viel sagen. Aber schön, dass es voran geht 👍

2021-03-10 19:16 UTC, Sataniel98 commented on pom.xml
> +    <version>1.0-RC-08</version>
Grundsätzlich sollten PRs keine Versionen ändern, ist aber nicht so schlimm.

2021-03-10 19:16 UTC, Sataniel98 commented on pom.xml
> -                    <execution>
Warum? Nein...

2021-03-10 19:16 UTC, Sataniel98 commented on src/main/java/de/erethon/caliburn/CaliburnAPI.java
> +    private final String identifierPrefix;
Umstrukturierungen und finals, die nichts mit dem Feature des PRs zu tun haben, sollten nicht rein.

2021-03-10 19:16 UTC, Sataniel98 commented on src/main/java/de/erethon/caliburn/recipe/CustomShapedRecipe.java
> +        return getKey().equals(obj);
Ist so etwas wie das gemeint?
```
if (!(obj instanceof CustomShapedRecipe)) {
    return false;
}
return getKey().equals(((CustomShapedRecipe) obj).getKey());
```
Oder was ist der Sinn davon?

2021-03-11 19:31 UTC, Fyreum commented on src/main/java/de/erethon/caliburn/recipe/CustomShapedRecipe.java
> +        return getKey().equals(obj);
Ja, die Abfrage habe ich wohl vergessen ^^

2021-03-11 19:32 UTC, Fyreum commented on pom.xml
> -                    <execution>
Ich weiß gar nicht, was da passiert ist. Erinnere mich nicht daran, da etwas geändert zu haben O.o

2021-03-11 19:34 UTC, Fyreum commented on pom.xml
> +    <version>1.0-RC-08</version>
Ok, das wusste ich nicht. Hatte die Version erhöht, um die Änderungen richtig testen zu können. Werde ich mir für die Zukunft merken

2021-03-11 19:35 UTC, Fyreum commented on src/main/java/de/erethon/caliburn/category/Category.java
> +    public static final Category<ExItem> BASE_STONE_OVERWORLD = new Category<>("base_stone_overworld", STONE, GRANITE, DIORITE, ANDESITE);
Das war wohl IntelliJ, keine Ahnung

2021-03-11 19:39 UTC, Fyreum commented on src/main/java/de/erethon/caliburn/CaliburnAPI.java
> +    private final String identifierPrefix;
Ist bei mir so eine Angewohnheit. IntelliJ meckert deswegen immer und ich ändere das schon fast unterbewusst.

2021-03-11 19:47 UTC, Fyreum commented on src/main/java/de/erethon/caliburn/item/CustomItem.java
> +
Schätze mal, dass IntelliJ die anders sortiert hat. Keine Ahnung warum ^^

2021-04-25 17:15 UTC, Sataniel98 commented
-> 2.0

2021-04-25 17:15 UTC, closed without merging